'use client';

import { Box, Container, Divider, Stack, Typography } from '@mui/material';

export default function TermsOfServicePage() {
  return (
    <Container maxWidth="md" sx={{ py: { xs: 6, md: 8 } }}>
      <Stack spacing={3}>
        <Stack spacing={1}>
          <Typography variant="h3" fontWeight={700}>
            Helix AI Intelligence Platform — Terms of Service
          </Typography>
          <Typography color="text.secondary">Effective Date: November 20, 2025</Typography>
          <Typography color="text.secondary">Entity: SinLess Games LLC</Typography>
          <Typography color="text.secondary">Contact: support@sinlessgames.com</Typography>
        </Stack>
        <Divider />
        <Stack spacing={3}>
          <Section
            title="1. Acceptance of Terms"
            body={
              <>
                <p>
                  By accessing or using the Helix AI Intelligence Platform (“Helix,” “Platform,” “Service”),
                  including the Helix Web App, Helix API, Helix AI Agents, Helix Discord Bot, Helix Mobile
                  Applications, Helix Plugins/Integrations/Extensions, or any software, system, model, or service
                  under the Helix name, you agree to be bound by these Terms. If you do not agree, do not use the Service.
                </p>
                <p>
                  These Terms apply globally and are governed first and primarily under Idaho law, and secondarily by
                  applicable local, national, and international laws.
                </p>
              </>
            }
          />
          <Section
            title="2. Eligibility"
            body="Helix imposes no age requirement. Users are responsible for compliance with local age-related laws in their jurisdiction."
          />
          <Section
            title="3. Description of the Service"
            body="Helix provides AI-driven tools for automation, analysis, support, communication, and general information. Helix includes evolving AI systems that may generate text, code, recommendations, or other outputs. Helix is provided by SinLess Games LLC."
          />
          <Section
            title="4. Account Registration"
            body={
              <>
                <p>You must provide accurate and complete information when creating an account and are responsible for all activity under your account.</p>
                <p>
                  Helix may terminate accounts for abuse, security threats, violations of law, non-payment, or violations of these
                  Terms.
                </p>
              </>
            }
          />
          <Section
            title="5. User Responsibilities"
            body={
              <>
                <p>Users agree to obey applicable laws, maintain credential security, and assume responsibility for all content generated with Helix.</p>
                <p>
                  Helix may produce incorrect, incomplete, harmful, or misleading outputs. You are solely responsible for how you use any
                  output generated by Helix.
                </p>
              </>
            }
          />
          <Section
            title="6. Prohibited Activities"
            body={
              <>
                <p>Users may not use Helix for illegal purposes; generate or distribute harmful code; create content for harassment, violence, hate, misinformation, or exploitation; reverse-engineer models or systems; scrape, overload, attack, or interfere with the Service; misuse outputs as legal, medical, financial, or professional advice; circumvent limits; or misrepresent Helix output as professional guidance.</p>
              </>
            }
          />
          <Section
            title="7. Commercial Use and Licensing"
            body={
              <>
                <p>Businesses may use Helix commercially only with an approved commercial license from SinLess Games LLC.</p>
                <p>Users own the output they generate, including rights to use, publish, and monetize it. Helix retains all rights to underlying models, systems, architecture, and core technologies.</p>
              </>
            }
          />
          <Section
            title="8. Content and Moderation"
            body="SinLess Games LLC may remove, restrict, or report content or accounts that violate law, threaten security, abuse or interfere with the service, or pose risks to users or infrastructure. Moderation may occur without notice."
          />
          <Section
            title="9. Payments, Subscriptions, and Refunds"
            body="Helix may offer paid tiers. All charges are final; no refunds for subscriptions, credits, or one-time purchases. Non-payment or chargebacks may result in suspension or termination."
          />
          <Section
            title="10. Intellectual Property"
            body={
              <>
                <p>All Helix systems, branding, documentation, code, models, and infrastructure remain the intellectual property of SinLess Games LLC.</p>
                <p>User-generated output is owned by the user, subject to compliance with these Terms. You may not represent Helix systems as your own, redistribute Helix models/infrastructure, or attempt to replicate Helix in violation of these Terms.</p>
              </>
            }
          />
          <Section
            title="11. Data Policy and Privacy"
            body="See the Helix Privacy Policy and Helix Data Policy for details on collection, processing, retention, and your rights. By using Helix, you agree to those policies."
          />
          <Section
            title="12. Disclaimers"
            body="Helix is provided “AS IS” and “AS AVAILABLE.” SinLess Games LLC provides no warranties and does not guarantee accuracy, safety, reliability, availability, fitness, protection from data loss, validity of AI content, or suitability for legal/medical/financial/professional decisions. Use at your own risk."
          />
          <Section
            title="13. Limitation of Liability"
            body="To the fullest extent permitted by law, SinLess Games LLC is not liable for indirect, incidental, consequential, punitive, or special damages, nor for data loss, lost profits, system failures, or interruptions. Your sole remedy is to discontinue use."
          />
          <Section
            title="14. Indemnification"
            body="You agree to indemnify and hold harmless SinLess Games LLC, its owners, employees, contractors, and affiliates from claims, damages, liabilities, or expenses arising from your use of Helix, your content/output, or violations of these Terms or law."
          />
          <Section
            title="15. Arbitration and Dispute Resolution"
            body="All disputes are resolved by binding arbitration in the State of Idaho under Idaho law. If arbitration is unavailable or invalidated, the matter is decided in a court of competent jurisdiction within Idaho. Users consent to Idaho jurisdiction and venue."
          />
          <Section
            title="16. Changes to the Terms"
            body="SinLess Games LLC may modify these Terms at any time. Changes take immediate effect upon posting. Continued use constitutes acceptance."
          />
          <Section
            title="17. Termination"
            body="SinLess Games LLC may suspend or terminate access at its sole discretion for abuse, security risks, non-payment, legal violations, or violations of these Terms, with or without prior notice."
          />
          <Section
            title="18. Contact Information"
            body="For questions, licensing, or support: SinLess Games LLC — support@sinlessgames.com"
          />
        </Stack>
      </Stack>
    </Container>
  );
}

type SectionProps = { title: string; body: React.ReactNode };

function Section({ title, body }: SectionProps) {
  return (
    <Box sx={{ display: 'grid', gap: 1.25 }}>
      <Typography variant="h6" fontWeight={600}>
        {title}
      </Typography>
      <Typography color="text.secondary" component="div" sx={{ display: 'grid', gap: 1 }}>
        {body}
      </Typography>
    </Box>
  );
}
