milestones:
  - title: 'Initial Release'
    state: 'open'
    description: 'First release of the project'
    due_on: '2023-12-31T23:59:59Z'
  - title: 'Version V1.0.0'
    state: 'open'
    description: 'Minor improvements and bug fixes'
  - title: 'User Interface'
    state: 'open'
    description: 'Milestone for user interface improvements'
  - title: 'Security'
    state: 'open'
    description: 'Milestone for security enhancements'
  - title: 'APIs'
    state: 'open'
    description: 'Milestone for API development'
  - title: 'UX'
    state: 'open'
    description: 'Milestone for user experience improvements'
  - title: 'Discord Bot'
    state: 'open'
    description: 'Milestone for Discord bot integration'
    due_on: '2025-09-30T23:59:59Z'
