// libs/db/src/entities/system/notification.entity.ts

import {
  Entity,
  Property,
  Index,
  ManyToOne,
  type Rel,
} from '@mikro-orm/core';
import { BaseEntity } from '../../entity.base';
import { User } from '../user/user.entity';

/**
 * Notification
 *
 * Represents an in-app or system-level notification sent to a {@link User}.
 * Notifications can be generated by system events, user actions,
 * or external integrations (e.g., payments, tickets, security alerts).
 *
 * Table: system_notification
 */
@Entity({ tableName: 'system_notification' })
@Index({ name: 'idx_notification_user_unread', properties: ['user', 'read'] })
export class Notification extends BaseEntity {
  /** Recipient user (FK). */
  @ManyToOne(() => User, { inversedBy: 'notifications', fieldName: 'user_id', nullable: false })
  user!: Rel<User>;

  /** Short title summarizing the purpose of the notification. */
  @Property({ type: 'text' })
  title!: string;

  /** Full message content. May contain Markdown or HTML. */
  @Property({ type: 'text' })
  message!: string;

  /** Whether this notification has been read by the user. */
  @Property({ type: 'boolean', default: false })
  read = false;

  /** Optional structured metadata for context (links, categories, actions). */
  @Property({ type: 'jsonb', nullable: true })
  metadata?: Record<string, unknown>;
}
