packages:
  - frontend
  - apis/*
  - libs/*


onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - nx
  - protobufjs
  - sharp
  - es5-ext
  - node-sass
