# Taskfile.yaml
# $schema: "https://raw.githubusercontent.com/go-task/taskfile/master/taskfile.schema.json"

version: "3"

vars:
  # Directories
  TASKFILE_DIR: "./.taskfiles"
  
# includes:

tasks:
  default:
    cmd: task --list-all

  new-release:
    desc: "Create a new release with changelog, tag, GitHub release, and artifacts"
    cmd: "./scripts/repo/release.sh"
    silent: false
    
  kill-port-3000:
    desc: "Kill any process running on port 3000"
    cmds:
      - |
        pid=$(lsof -t -i :3000)
        if [ -n "$pid" ]; then
          echo "Killing process(es) on port 3000: $pid"
          kill -9 $pid
        else
          echo "✅ No process running on port 3000"
        fi
    silent: false