export const InnovationCriteria = [
  'User Impact: Does it significantly improve productivity or decision-making?',
  'Explainability: Can users understand and trust the AI’s suggestions?',
  'Scalability: Is the solution designed to grow with diverse use cases and data volumes?',
  'Performance: Does it operate efficiently under expected loads?',
  'Usability: Is the interface intuitive and easy to navigate?',
  'Accessibility: Does it meet accessibility standards for all users?',
  'Security: Are user data and operations protected against threats?',
  'Privacy: Does it safeguard user information and comply with regulations?',
  'Interoperability: Can it integrate seamlessly with other systems?',
  'Maintainability: Is the codebase organized for easy updates and fixes?',
  'Extensibility: Can new features be added with minimal rework?',
  'Reliability: Does it function consistently under various conditions?',
  'Robustness: Can it handle unexpected inputs and errors gracefully?',
  'Flexibility: Is it adaptable to changing requirements?',
  'Cost-effectiveness: Does it provide value relative to its development and operational costs?',
  'Ethical Compliance: Does it adhere to ethical guidelines and standards?',
  'Transparency: Are all processes fully visible and documented?',
  'Auditability: Can actions and decisions be traced and reviewed?',
  'Community Engagement: Does it encourage contributions and feedback from users?',
  'Localization: Does it support multiple languages and regional settings?',
]
