name: Labeler

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *' # schedule still defined, but labeler will skip if not a PR

permissions:
  contents: read       # to checkout and scan files
  pull-requests: write # to add labels on PRs
  issues: write        # needed to create labels if they don’t exist

env:
  IS_PR: false

jobs:
  labeler:
    name: Apply Labels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect pull request
        id: detect_pr
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "IS_PR=true" >> $GITHUB_ENV
          else
            echo "IS_PR=false" >> $GITHUB_ENV
          fi

      - name: Run Labeler
        if: env.IS_PR == 'true'
        uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yaml
          sync-labels: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
