name: Meticulous

on:
  push:
    branches: [ master ]
  pull_request: {}
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write
  statuses: read

jobs:
  test:
    name: Meticulous
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # 2) Setup Node.js (v20) + Corepack (pnpm)
      - name: Setup Node.js & enable pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 3) Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      # 4) Build your app
      - name: Build project
        run: task frontend:build

      # 6) Publish the static folder to Meticulous
      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action/upload-assets@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          app-directory: out
